[2022-02-03 14:39:22,548] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-05-01T00:00:00+00:00 [queued]>
[2022-02-03 14:39:22,563] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-05-01T00:00:00+00:00 [queued]>
[2022-02-03 14:39:22,564] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 14:39:22,565] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-03 14:39:22,565] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 14:39:22,583] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-05-01 00:00:00+00:00
[2022-02-03 14:39:22,589] {standard_task_runner.py:52} INFO - Started process 907 to run task
[2022-02-03 14:39:22,599] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'FHV_data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-05-01T00:00:00+00:00', '--job-id', '439', '--raw', '--subdir', 'DAGS_FOLDER/FHV_injection_dag.py', '--cfg-path', '/tmp/tmpq1ofcp05', '--error-file', '/tmp/tmpdo7ocvxx']
[2022-02-03 14:39:22,603] {standard_task_runner.py:77} INFO - Job 439: Subtask local_to_gcs_task
[2022-02-03 14:39:22,672] {logging_mixin.py:109} INFO - Running <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-05-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-03 14:39:22,713] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-03 14:39:22,757] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=FHV_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-05-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-05-01T00:00:00+00:00
[2022-02-03 14:39:31,856] {python.py:175} INFO - Done. Returned value was: None
[2022-02-03 14:39:31,875] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=FHV_data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20190501T000000, start_date=20220203T143922, end_date=20220203T143931
[2022-02-03 14:39:31,919] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-03 14:39:31,989] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-03 15:08:07,987] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-05-01T00:00:00+00:00 [queued]>
[2022-02-03 15:08:08,004] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-05-01T00:00:00+00:00 [queued]>
[2022-02-03 15:08:08,005] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 15:08:08,005] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-03 15:08:08,006] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 15:08:08,032] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-05-01 00:00:00+00:00
[2022-02-03 15:08:08,042] {standard_task_runner.py:52} INFO - Started process 2675 to run task
[2022-02-03 15:08:08,048] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'FHV_data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-05-01T00:00:00+00:00', '--job-id', '542', '--raw', '--subdir', 'DAGS_FOLDER/FHV_injection_dag.py', '--cfg-path', '/tmp/tmpl8ywk86x', '--error-file', '/tmp/tmpm_q4x83y']
[2022-02-03 15:08:08,052] {standard_task_runner.py:77} INFO - Job 542: Subtask local_to_gcs_task
[2022-02-03 15:08:08,148] {logging_mixin.py:109} INFO - Running <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-05-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-03 15:08:08,204] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-03 15:08:08,248] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=FHV_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-05-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-05-01T00:00:00+00:00
[2022-02-03 15:08:12,658] {python.py:175} INFO - Done. Returned value was: None
[2022-02-03 15:08:12,679] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=FHV_data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20190501T000000, start_date=20220203T150807, end_date=20220203T150812
[2022-02-03 15:08:12,720] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-03 15:08:12,768] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
