[2022-02-03 14:38:24,279] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2022-02-03 14:38:24,295] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2022-02-03 14:38:24,297] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 14:38:24,297] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-03 14:38:24,298] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 14:38:24,316] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-04-01 00:00:00+00:00
[2022-02-03 14:38:24,324] {standard_task_runner.py:52} INFO - Started process 834 to run task
[2022-02-03 14:38:24,329] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'FHV_data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '435', '--raw', '--subdir', 'DAGS_FOLDER/FHV_injection_dag.py', '--cfg-path', '/tmp/tmpx98i765k', '--error-file', '/tmp/tmpw6fdybdp']
[2022-02-03 14:38:24,331] {standard_task_runner.py:77} INFO - Job 435: Subtask local_to_gcs_task
[2022-02-03 14:38:24,430] {logging_mixin.py:109} INFO - Running <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-04-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-03 14:38:24,482] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-03 14:38:24,512] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=FHV_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-01T00:00:00+00:00
[2022-02-03 14:38:27,367] {python.py:175} INFO - Done. Returned value was: None
[2022-02-03 14:38:27,424] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=FHV_data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20190401T000000, start_date=20220203T143824, end_date=20220203T143827
[2022-02-03 14:38:27,523] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-03 14:38:27,582] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-03 15:08:09,382] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2022-02-03 15:08:09,395] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2022-02-03 15:08:09,396] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 15:08:09,396] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-03 15:08:09,397] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 15:08:09,408] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-04-01 00:00:00+00:00
[2022-02-03 15:08:09,414] {standard_task_runner.py:52} INFO - Started process 2683 to run task
[2022-02-03 15:08:09,418] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'FHV_data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '543', '--raw', '--subdir', 'DAGS_FOLDER/FHV_injection_dag.py', '--cfg-path', '/tmp/tmp8d1tr6y9', '--error-file', '/tmp/tmpvce2vuuu']
[2022-02-03 15:08:09,420] {standard_task_runner.py:77} INFO - Job 543: Subtask local_to_gcs_task
[2022-02-03 15:08:09,483] {logging_mixin.py:109} INFO - Running <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-04-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-03 15:08:09,533] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-03 15:08:09,554] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=FHV_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-01T00:00:00+00:00
[2022-02-03 15:08:11,981] {python.py:175} INFO - Done. Returned value was: None
[2022-02-03 15:08:12,000] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=FHV_data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20190401T000000, start_date=20220203T150809, end_date=20220203T150812
[2022-02-03 15:08:12,034] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-03 15:08:12,067] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
