[2022-02-03 15:02:12,754] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-04-01T00:00:00+00:00 [queued]>
[2022-02-03 15:02:12,798] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-04-01T00:00:00+00:00 [queued]>
[2022-02-03 15:02:12,800] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 15:02:12,803] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-03 15:02:12,806] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 15:02:12,851] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-04-01 00:00:00+00:00
[2022-02-03 15:02:12,869] {standard_task_runner.py:52} INFO - Started process 2353 to run task
[2022-02-03 15:02:12,910] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'FHV_data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2021-04-01T00:00:00+00:00', '--job-id', '525', '--raw', '--subdir', 'DAGS_FOLDER/FHV_injection_dag.py', '--cfg-path', '/tmp/tmpa9sd6io4', '--error-file', '/tmp/tmpn2purpeq']
[2022-02-03 15:02:12,917] {standard_task_runner.py:77} INFO - Job 525: Subtask local_to_gcs_task
[2022-02-03 15:02:13,205] {logging_mixin.py:109} INFO - Running <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-04-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-03 15:02:13,333] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-03 15:02:13,396] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=FHV_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-01T00:00:00+00:00
[2022-02-03 15:02:15,433] {python.py:175} INFO - Done. Returned value was: None
[2022-02-03 15:02:15,462] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=FHV_data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20210401T000000, start_date=20220203T150212, end_date=20220203T150215
[2022-02-03 15:02:15,526] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-03 15:02:15,623] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-03 15:21:03,012] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-04-01T00:00:00+00:00 [queued]>
[2022-02-03 15:21:03,028] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-04-01T00:00:00+00:00 [queued]>
[2022-02-03 15:21:03,029] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 15:21:03,031] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-03 15:21:03,031] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 15:21:03,043] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-04-01 00:00:00+00:00
[2022-02-03 15:21:03,049] {standard_task_runner.py:52} INFO - Started process 3692 to run task
[2022-02-03 15:21:03,052] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'FHV_data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2021-04-01T00:00:00+00:00', '--job-id', '612', '--raw', '--subdir', 'DAGS_FOLDER/FHV_injection_dag.py', '--cfg-path', '/tmp/tmp_o2wqrqt', '--error-file', '/tmp/tmpr8x6f4mu']
[2022-02-03 15:21:03,054] {standard_task_runner.py:77} INFO - Job 612: Subtask local_to_gcs_task
[2022-02-03 15:21:03,129] {logging_mixin.py:109} INFO - Running <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-04-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-03 15:21:03,197] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-03 15:21:03,225] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=FHV_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-01T00:00:00+00:00
[2022-02-03 15:21:05,226] {python.py:175} INFO - Done. Returned value was: None
[2022-02-03 15:21:05,242] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=FHV_data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20210401T000000, start_date=20220203T152103, end_date=20220203T152105
[2022-02-03 15:21:05,291] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-03 15:21:05,334] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
