[2022-02-03 14:58:27,341] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2020-11-01T00:00:00+00:00 [queued]>
[2022-02-03 14:58:27,374] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2020-11-01T00:00:00+00:00 [queued]>
[2022-02-03 14:58:27,376] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 14:58:27,378] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-03 14:58:27,380] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 14:58:27,430] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-11-01 00:00:00+00:00
[2022-02-03 14:58:27,443] {standard_task_runner.py:52} INFO - Started process 2111 to run task
[2022-02-03 14:58:27,467] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'FHV_data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2020-11-01T00:00:00+00:00', '--job-id', '505', '--raw', '--subdir', 'DAGS_FOLDER/FHV_injection_dag.py', '--cfg-path', '/tmp/tmp1xqapfmf', '--error-file', '/tmp/tmpsbqo1qws']
[2022-02-03 14:58:27,471] {standard_task_runner.py:77} INFO - Job 505: Subtask local_to_gcs_task
[2022-02-03 14:58:27,598] {logging_mixin.py:109} INFO - Running <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2020-11-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-03 14:58:27,687] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-03 14:58:27,739] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=FHV_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-11-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-11-01T00:00:00+00:00
[2022-02-03 14:58:30,033] {python.py:175} INFO - Done. Returned value was: None
[2022-02-03 14:58:30,055] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=FHV_data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20201101T000000, start_date=20220203T145827, end_date=20220203T145830
[2022-02-03 14:58:30,111] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-03 14:58:30,179] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-03 15:18:48,619] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2020-11-01T00:00:00+00:00 [queued]>
[2022-02-03 15:18:48,636] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2020-11-01T00:00:00+00:00 [queued]>
[2022-02-03 15:18:48,637] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 15:18:48,638] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-03 15:18:48,639] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 15:18:48,655] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-11-01 00:00:00+00:00
[2022-02-03 15:18:48,662] {standard_task_runner.py:52} INFO - Started process 3500 to run task
[2022-02-03 15:18:48,671] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'FHV_data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2020-11-01T00:00:00+00:00', '--job-id', '597', '--raw', '--subdir', 'DAGS_FOLDER/FHV_injection_dag.py', '--cfg-path', '/tmp/tmpezd1grfm', '--error-file', '/tmp/tmpwp0a2ugh']
[2022-02-03 15:18:48,674] {standard_task_runner.py:77} INFO - Job 597: Subtask local_to_gcs_task
[2022-02-03 15:18:48,742] {logging_mixin.py:109} INFO - Running <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2020-11-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-03 15:18:48,787] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-03 15:18:48,810] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=FHV_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-11-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-11-01T00:00:00+00:00
[2022-02-03 15:18:50,883] {python.py:175} INFO - Done. Returned value was: None
[2022-02-03 15:18:50,896] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=FHV_data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20201101T000000, start_date=20220203T151848, end_date=20220203T151850
[2022-02-03 15:18:50,935] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-03 15:18:50,965] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
