[2022-02-03 14:57:44,123] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2020-10-01T00:00:00+00:00 [queued]>
[2022-02-03 14:57:44,151] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2020-10-01T00:00:00+00:00 [queued]>
[2022-02-03 14:57:44,152] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 14:57:44,154] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-03 14:57:44,156] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 14:57:44,187] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-10-01 00:00:00+00:00
[2022-02-03 14:57:44,196] {standard_task_runner.py:52} INFO - Started process 2059 to run task
[2022-02-03 14:57:44,207] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'FHV_data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2020-10-01T00:00:00+00:00', '--job-id', '501', '--raw', '--subdir', 'DAGS_FOLDER/FHV_injection_dag.py', '--cfg-path', '/tmp/tmpmby9zzwt', '--error-file', '/tmp/tmpdx2846it']
[2022-02-03 14:57:44,211] {standard_task_runner.py:77} INFO - Job 501: Subtask local_to_gcs_task
[2022-02-03 14:57:44,330] {logging_mixin.py:109} INFO - Running <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2020-10-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-03 14:57:44,405] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-03 14:57:44,463] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=FHV_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-10-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-10-01T00:00:00+00:00
[2022-02-03 14:57:46,535] {python.py:175} INFO - Done. Returned value was: None
[2022-02-03 14:57:46,582] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=FHV_data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20201001T000000, start_date=20220203T145744, end_date=20220203T145746
[2022-02-03 14:57:46,785] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-03 14:57:46,885] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-03 15:18:06,280] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2020-10-01T00:00:00+00:00 [queued]>
[2022-02-03 15:18:06,294] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2020-10-01T00:00:00+00:00 [queued]>
[2022-02-03 15:18:06,295] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 15:18:06,295] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-03 15:18:06,296] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 15:18:06,312] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-10-01 00:00:00+00:00
[2022-02-03 15:18:06,323] {standard_task_runner.py:52} INFO - Started process 3453 to run task
[2022-02-03 15:18:06,334] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'FHV_data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2020-10-01T00:00:00+00:00', '--job-id', '594', '--raw', '--subdir', 'DAGS_FOLDER/FHV_injection_dag.py', '--cfg-path', '/tmp/tmp05ih9o_h', '--error-file', '/tmp/tmpih3krjfh']
[2022-02-03 15:18:06,335] {standard_task_runner.py:77} INFO - Job 594: Subtask local_to_gcs_task
[2022-02-03 15:18:06,396] {logging_mixin.py:109} INFO - Running <TaskInstance: FHV_data_ingestion_gcs_dag.local_to_gcs_task scheduled__2020-10-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-03 15:18:06,444] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-03 15:18:06,463] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=FHV_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-10-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-10-01T00:00:00+00:00
[2022-02-03 15:18:08,366] {python.py:175} INFO - Done. Returned value was: None
[2022-02-03 15:18:08,384] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=FHV_data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20201001T000000, start_date=20220203T151806, end_date=20220203T151808
[2022-02-03 15:18:08,427] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-03 15:18:08,467] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
