[2022-02-02 19:11:45,029] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-07-01T00:00:00+00:00 [queued]>
[2022-02-02 19:11:45,047] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-07-01T00:00:00+00:00 [queued]>
[2022-02-02 19:11:45,049] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 19:11:45,050] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-02 19:11:45,051] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 19:11:45,068] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-07-01 00:00:00+00:00
[2022-02-02 19:11:45,080] {standard_task_runner.py:52} INFO - Started process 11815 to run task
[2022-02-02 19:11:45,090] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2021-07-01T00:00:00+00:00', '--job-id', '394', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmp6zuqzrs8', '--error-file', '/tmp/tmpr3_cqbhy']
[2022-02-02 19:11:45,094] {standard_task_runner.py:77} INFO - Job 394: Subtask local_to_gcs_task
[2022-02-02 19:11:45,184] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-07-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-02 19:11:45,238] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-02 19:11:45,274] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-07-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-01T00:00:00+00:00
[2022-02-02 19:11:51,069] {python.py:175} INFO - Done. Returned value was: None
[2022-02-02 19:11:51,085] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20210701T000000, start_date=20220202T191145, end_date=20220202T191151
[2022-02-02 19:11:51,143] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-02 19:11:51,179] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 14:53:22,795] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-07-01T00:00:00+00:00 [queued]>
[2022-02-10 14:53:22,827] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-07-01T00:00:00+00:00 [queued]>
[2022-02-10 14:53:22,829] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 14:53:22,832] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 14:53:22,834] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 14:53:22,868] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-07-01 00:00:00+00:00
[2022-02-10 14:53:22,884] {standard_task_runner.py:52} INFO - Started process 3474 to run task
[2022-02-10 14:53:22,893] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2021-07-01T00:00:00+00:00', '--job-id', '748', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmpw5094qnc', '--error-file', '/tmp/tmpet25rhcx']
[2022-02-10 14:53:22,899] {standard_task_runner.py:77} INFO - Job 748: Subtask local_to_gcs_task
[2022-02-10 14:53:23,116] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-07-01T00:00:00+00:00 [running]> on host e30f201fae61
[2022-02-10 14:53:23,236] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 14:53:23,280] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-07-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-01T00:00:00+00:00
[2022-02-10 14:53:32,870] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 14:53:32,902] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20210701T000000, start_date=20220210T145322, end_date=20220210T145332
[2022-02-10 14:53:32,963] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 14:53:33,042] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 15:42:49,041] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-07-01T00:00:00+00:00 [queued]>
[2022-02-10 15:42:49,060] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-07-01T00:00:00+00:00 [queued]>
[2022-02-10 15:42:49,061] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 15:42:49,063] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 15:42:49,064] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 15:42:49,083] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-07-01 00:00:00+00:00
[2022-02-10 15:42:49,094] {standard_task_runner.py:52} INFO - Started process 1204 to run task
[2022-02-10 15:42:49,108] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2021-07-01T00:00:00+00:00', '--job-id', '877', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmpyj4_gy1l', '--error-file', '/tmp/tmp0eishnoa']
[2022-02-10 15:42:49,112] {standard_task_runner.py:77} INFO - Job 877: Subtask local_to_gcs_task
[2022-02-10 15:42:49,245] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-07-01T00:00:00+00:00 [running]> on host 276a0ad90304
[2022-02-10 15:42:49,369] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 15:42:49,406] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-07-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-01T00:00:00+00:00
[2022-02-10 15:43:08,888] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 15:43:08,910] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20210701T000000, start_date=20220210T154249, end_date=20220210T154308
[2022-02-10 15:43:08,981] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 15:43:09,027] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 16:44:42,104] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-07-01T00:00:00+00:00 [queued]>
[2022-02-10 16:44:42,124] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-07-01T00:00:00+00:00 [queued]>
[2022-02-10 16:44:42,125] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:44:42,127] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 16:44:42,128] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:44:42,152] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-07-01 00:00:00+00:00
[2022-02-10 16:44:42,165] {standard_task_runner.py:52} INFO - Started process 1022 to run task
[2022-02-10 16:44:42,171] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2021-07-01T00:00:00+00:00', '--job-id', '985', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmp3dx9i34k', '--error-file', '/tmp/tmpsbbb_bag']
[2022-02-10 16:44:42,172] {standard_task_runner.py:77} INFO - Job 985: Subtask local_to_gcs_task
[2022-02-10 16:44:42,276] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-07-01T00:00:00+00:00 [running]> on host 106a34111faf
[2022-02-10 16:44:42,332] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 16:44:42,365] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-07-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-01T00:00:00+00:00
[2022-02-10 16:45:07,789] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 16:45:07,808] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20210701T000000, start_date=20220210T164442, end_date=20220210T164507
[2022-02-10 16:45:07,846] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 16:45:07,890] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
